- name: Playbook 2 - Configure Master-Slave Replication
  hosts: carrier
  become: true

  tasks:
    - name: Start DB slave service
      community.docker.docker_compose_v2:
        project_src: "{{ app_dir }}"
        services:
          - "{{ mysql_slave }}"
        pull: missing
        recreate: never
        remove_orphans: true

    - name: Wait until slave MySQL is ready
      ansible.builtin.wait_for:
        host: localhost
        port: 3307
        state: started
        delay: 5
        timeout: 120

    - name: Configure MySQL master-slave replication
      ansible.builtin.include_role:
        name: wordpress
        tasks_from: cluster

    - name: Show replication configuration info
      ansible.builtin.debug:
        msg:
          - "wordpress: {{ is_wordpress }}"
          - "wordpress_port: {{ wordpress_port }}"
          - "wordpress_db_name: {{ wordpress_db_name }}"
          - "mysql_master: {{ mysql_master }}"
          - "mysql_slave: {{ mysql_slave }}"
          - "wordpress_db_root_password: {{ wordpress_db_root_password }}"